### ISSUE TITLE
Different default branch name

### ISSUE THREAD

**Issue by Azd325** [chezmoi/dotfiles#3]
I started to use this template, and I was wondering why the CI didn't run and saw that it set explicit set to master.
Currently, I use `main`.  I could imagine that is fine to let run on every branch at least for the push events because normally dot files are maintained only from a single person.

https://github.com/chezmoi/dotfiles/blob/52300a4de42bcb955f42c6d2f6270e8d6625b43b/.github/workflows/ci.yaml#L5-L7

Also, I didn't find that GitHub Actions offers an environment variable for the default branch to catch this.

**Comment by twpayne** [comment]
Thanks for catching and suggesting this. I've implemented it in ba46566ff24c9750a86a9c2a2026d0d462fa312e.
